### ISSUE TITLE
German hyphenation wrong

### ISSUE THREAD

**Issue by leoc** [halostatue/text-hyphen#13]
Hi, I stumbled upon this gem and tried it to generate soft hyphens for a web project.
Unfortunately the german hyphenation seems to be buggy.

```ruby
require 'text-hyphen'
h = Text::Hyphen.new(language:'de1', left:2, right:2)
h.visualize('Innerhalb kürzester Zeit usw.') # => "Inner-halb -kür-zes-ter -Zeit usw."
```

The hyphen in front of the word "kürzester" or "Zeit" are annoying.

Maybe you have a quick hint? Thanks!

**Comment by tnt** [comment]
@leoc I think `visualize()` expects a word not texts of arbitrary lengths. Everything looks fine if you do it like this:

```ruby
'Innerhalb kürzester Zeit usw.'.split(' ').map {|w| h.visualize(w) }.join ' '
```

The underlying algorithm is known to give qiet good results. Unfortunately this implemetation is incompletely documented. Normally (when working with TeX/LaTeX) you need to define *exceptions* for special words that are not correctly hyphenated. I can't find out how to do this other than this way:

```ruby
h.language.exceptions["zeit"] = [0,0,1,0,0]
``` 

Or you add a method like this:

```ruby
class Text::Hyphen
  def add_exception exc
    poss, off = [], 0
    exc.chars.each_with_index {|c, n| c == '-' && poss << n - off && off += 1}
    exc_arr = (0..exc.size-off).map {|i| poss.include?(i) ? 1 : 0}
    language.exceptions[exc.gsub('-', '')] = exc_arr
  end
  # or shorter
  def add_exception exc
    exc_arr = "#{exc}.".gsub(/-./, '-').each_char.map {|c| c == '-' ? 1 : 0}
    language.exceptions[exc.gsub('-', '')] = exc_arr
  end
end
```
If you then do

```ruby
h.add_exception 'zu-rück-blei-ben'
h.visualize 'zurückbleiben', '&shy;'
```
you will get `'zu&shy;rück&shy;blei&shy;ben'` instead of `'zurück&shy;blei&shy;ben'` .

**Comment by leoc** [comment]
Thanks. This is how I worked around the error (splitting Sentences to words, visualizing and joining again). I thought this might be a bug and not expected behaviour.

```ruby
# Replacing words, without punctuation
text.gsub!(WORD_REGEX) do |word|
  @de.visualize(word, '&shy;')
end
```

Thanks for the hint about the exceptions!

**Comment by halostatue** [comment]
Thanks, @tnt, for looking into this and answering the question for @leoc. I have (sadly) not had the time to look into this and am not as familiar with German hyphenation as I perhaps should be with this module.
